[2023-11-23T08:20:16.078+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Data_transfer.Create_table scheduled__2023-11-23T07:49:10.491939+00:00 [queued]>
[2023-11-23T08:20:16.095+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Data_transfer.Create_table scheduled__2023-11-23T07:49:10.491939+00:00 [queued]>
[2023-11-23T08:20:16.095+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T08:20:16.096+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 3
[2023-11-23T08:20:16.096+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-11-23T08:20:16.118+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): Create_table> on 2023-11-23 07:49:10.491939+00:00
[2023-11-23T08:20:16.126+0000] {standard_task_runner.py:55} INFO - Started process 10522 to run task
[2023-11-23T08:20:16.131+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Data_transfer', 'Create_table', 'scheduled__2023-11-23T07:49:10.491939+00:00', '--job-id', '651', '--raw', '--subdir', 'DAGS_FOLDER/data_transfer.py', '--cfg-path', '/tmp/tmp1tj1uz4m']
[2023-11-23T08:20:16.134+0000] {standard_task_runner.py:83} INFO - Job 651: Subtask Create_table
[2023-11-23T08:20:16.219+0000] {task_command.py:376} INFO - Running <TaskInstance: Data_transfer.Create_table scheduled__2023-11-23T07:49:10.491939+00:00 [running]> on host f71f95879a41
[2023-11-23T08:20:16.328+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gaurav
AIRFLOW_CTX_DAG_ID=Data_transfer
AIRFLOW_CTX_TASK_ID=Create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-11-23T07:49:10.491939+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-11-23T07:49:10.491939+00:00
[2023-11-23T08:20:16.339+0000] {base.py:71} INFO - Using connection ID 'source_db_***' for task execution.
[2023-11-23T08:20:16.346+0000] {sql.py:315} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS ***_users (
        uuid TEXT NOT NULL,
        title TEXT NOT NULL,
        firstname TEXT NOT NULL,
        lastname TEXT NOT NULL,
        gender TEXT NOT NULL,
        country TEXT NOT NULL,
        username TEXT NOT NULL,
        password TEXT NOT NULL,
        email TEXT NOT NULL,
        age INT NOT NULL
        )
        , parameters: None
[2023-11-23T08:20:16.349+0000] {postgres.py:96} INFO - NOTICE:  relation "***_users" already exists, skipping

[2023-11-23T08:20:16.360+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=Data_transfer, task_id=Create_table, execution_date=20231123T074910, start_date=20231123T082016, end_date=20231123T082016
[2023-11-23T08:20:16.382+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-11-23T08:20:16.405+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
